name: rmus
description: "Experimental music player made with Flutter & rust"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.16.5

dependencies:
  cached_network_image: ^3.2.3
  chopper: ^7.0.6
  cupertino_icons: ^1.0.5
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_rust_bridge: 2.0.0-dev.22
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.2
  go_router: ^13.1.0
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.0
  path: ^1.8.3
  path_provider: ^2.0.13
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.0.18
  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  chopper_generator: ^7.0.4
  custom_lint: ^0.6.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  linteo: ^1.1.0
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.9
  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/